module.exports = {
  addConstant: require('./add-constant'),
  atLeast2d: require('./at-least-2d'),
  checkConvergence: require('./check-convergence'),
  clone: require('./clone'),
  constantize: require('./constantize'),
  dot: require('./dot'),
  identity: require('./identity'),
  inverse: require('./inverse'),
  isArray: require('./is-array'),
  makeArray: require('./make-array'),
  map: require('./map'),
  mean: require('./mean'),
  mul: require('./mul'),
  norm1: require('./norm1'),
  norm2: require('./norm2'),
  norminf: require('./norminf'),
  scalarmul: require('./scalarmul'),
  shape: require('./shape'),
  sign: require('./sign'),
  sub: require('./sub'),
  sum: require('./sum'),
  transpose: require('./transpose'),
  zeros: require('./zeros')
};
